<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="SWITCH-PC10" failures="0" tests="1" name="Default test" time="3.847" errors="0" timestamp="2023-06-02T11:54:55 IST">
  <testcase classname="testcases_Personalizationprocess_Authorized_Cards.Authorized_Cards_By_Filter_All" name="@AfterTest endTest" time="0.835">
    <failure type="java.io.IOException" message="Failed to open file:/C:/Users/gokul/CGS_AUtomation_Projects/SIB_Project/report.html. Error message: The system cannot find the file specified.
">
      <![CDATA[java.io.IOException: Failed to open file:/C:/Users/gokul/CGS_AUtomation_Projects/SIB_Project/report.html. Error message: The system cannot find the file specified.

at java.desktop/sun.awt.windows.WDesktopPeer.ShellExecute(WDesktopPeer.java:115)
at java.desktop/sun.awt.windows.WDesktopPeer.browse(WDesktopPeer.java:101)
at java.desktop/java.awt.Desktop.browse(Desktop.java:533)
at testcases_Personalizationprocess_Authorized_Cards.Authorized_Cards_By_Filter_All.endTest(Authorized_Cards_By_Filter_All.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.afterRun(TestRunner.java:877)
at org.testng.TestRunner.run(TestRunner.java:599)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterTest endTest -->
  <testcase classname="testcases_Personalizationprocess_Authorized_Cards.Authorized_Cards_By_Filter_All" name="authorizecardsAll" time="2.616"/>
  <testcase classname="testcases_Personalizationprocess_Authorized_Cards.Authorized_Cards_By_Filter_All" name="browser" time="0.0">
    <ignored/>
  </testcase> <!-- browser -->
</testsuite> <!-- Default test -->
